### ISSUE TITLE
Recipe is no longer updating

### ISSUE THREAD

**Issue by urschrei** [conda-forge/pyzotero-feedstock#26]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

@moorepants Sorry to ping you, but I'm only an occasional Anaconda user – the recipe is no longer updating. I restructured the package (Python 3 only, using `pyproject.toml` + `setup.cfg`) to incorporate new best practices but I don't know whether that's the issue. Let me know if there's anything I can do from my end…

**Comment by moorepants** [comment]
As far as I understand we have to delete pyproject.toml files in conda forge, because it's a conflict. Conda's meta.yaml is a build instruction and so is pyproject.toml. See: https://github.com/conda-forge/conda-forge.github.io/issues/1174

**Comment by moorepants** [comment]
Lots of recipes have this:

```
- {{ PYTHON }} -c "__import__('os').unlink('pyproject.toml')"
- {{ PYTHON }} -m pip install . -vv
```

**Comment by urschrei** [comment]
Ah, OK!

**Comment by moorepants** [comment]
If that doesn't work I put a `rm pyproject.toml` or for windows `del pyproject.toml` before install. I think that works too.

**Comment by moorepants** [comment]
I can make a PR with the update if you want.

**Comment by urschrei** [comment]
Oh, thanks! There are also some requirements simplifications, minimum Python >=3.6, and we now depend on pytest for testing: https://github.com/urschrei/pyzotero/blob/ed4175e0f1a62f10984b311864c13ac453fa9ebe/setup.cfg#L35-L47

**Comment by moorepants** [comment]
See #27

**Comment by moorepants** [comment]
There is a PR here with the possible official recommendations: https://github.com/conda-forge/conda-forge.github.io/pull/1540

**Comment by moorepants** [comment]
I'm not sure how that will play out. The pyproject.toml is effectively build instructions, just like conda's meta.yaml and any other package manager's spec file. Maybe there will be a way to extract info from the pyproject.toml file to be incorporated into a package manager's spec file.

**Comment by moorepants** [comment]
Maybe something like: https://github.com/dojeda/poetry2conda
